import { Organizer } from "./OrganizerService";
import { TestService } from "./TestService";

export interface HeinAnalysisResult {
    analysis: string;
    essayTopic: string;
    essayType: string;
    scope: string;
    structure: string;
}

export class HeinService {
    static async analyze(): Promise<HeinAnalysisResult> {
        if (TestService.isActive) {
            const mock = await TestService.getAnalysis();
            const result: HeinAnalysisResult = {
                analysis: "Mock analysis generated by test mode.",
                essayTopic: mock.topic,
                essayType: mock.essay_type,
                scope: mock.scope,
                structure: mock.structure
            };
            Organizer.set({
                analysis: result.analysis,
                essayTopic: result.essayTopic,
                analyzedEssayType: result.essayType,
                scope: result.scope,
                structure: result.structure,
            });
            return result;
        }

        const state = Organizer.get();

        const res = await fetch("/api/hein/analyze", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                major: state.majorName,
                essayType: state.essayType,
                instructions: state.instructions,
            }),
        });

        if (!res.ok) {
            const err = await res.json().catch(() => ({}));
            throw new Error(err.error || `Hein analysis failed: ${res.status}`);
        }

        const result: HeinAnalysisResult = await res.json();

        Organizer.set({
            analysis: result.analysis,
            essayTopic: result.essayTopic,
            analyzedEssayType: result.essayType,
            scope: result.scope,
            structure: result.structure,
        });

        return result;
    }
}
