// LunaService — client-side service to invoke the Luna analysis agent.
// Fetches API key + model dynamically from the backend, then calls the
// Next.js API route which proxies to OpenRouter.

import { Organizer } from "./OrganizerService";
import { TestService } from "./TestService";

export interface LunaAnalysisResult {
    analysis: string;
    essayTopic: string;
    essayType: string;
    scope: string;
    structure: string;
}

interface BackendKeyResponse {
    openrouter_api_key: string;
    brave_api_key: string;
    primary_model: string;
    secondary_model: string;
}

export class LunaService {
    /**
     * Fetch a random active OpenRouter API key + the current secondary model
     * from the backend key pool.
     */
    static async fetchConfig(): Promise<{ apiKey: string; model: string }> {
        const res = await fetch("https://api.octopilotai.com/api/v1/settings/keys");
        if (!res.ok) throw new Error("Failed to fetch API configuration from backend");
        const data: BackendKeyResponse = await res.json();

        if (!data.openrouter_api_key) {
            throw new Error("No active OpenRouter key available in the pool");
        }

        if (!data.secondary_model) {
            throw new Error("No secondary model configured in backend settings");
        }

        return {
            apiKey: data.openrouter_api_key,
            model: data.secondary_model,
        };
    }

    /**
     * Run Luna's analysis on the current Organizer state.
     * Updates the Organizer with results when done.
     */
    static async analyze(): Promise<LunaAnalysisResult> {
        if (TestService.isActive) {
            const mock = await TestService.getAnalysis();
            const result: LunaAnalysisResult = {
                analysis: "Mock analysis generated by test mode.",
                essayTopic: mock.topic,
                essayType: mock.essay_type,
                scope: mock.scope,
                structure: mock.structure
            };
            Organizer.set({
                analysis: result.analysis,
                essayTopic: result.essayTopic,
                analyzedEssayType: result.essayType,
                scope: result.scope,
                structure: result.structure,
            });
            return result;
        }

        const state = Organizer.get();

        // 1. Grab an API key + model from the backend pool
        const { apiKey, model } = await LunaService.fetchConfig();

        // 2. Call our Next.js API route
        const res = await fetch("/api/luna/analyze", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                major: state.majorName,
                essayType: state.essayType,
                instructions: state.instructions,
                apiKey,
                model,
            }),
        });

        if (!res.ok) {
            const err = await res.json().catch(() => ({}));
            throw new Error(err.error || `Luna analysis failed: ${res.status}`);
        }

        const result: LunaAnalysisResult = await res.json();

        // 3. Store results in the Organizer
        Organizer.set({
            analysis: result.analysis,
            essayTopic: result.essayTopic,
            analyzedEssayType: result.essayType,
            scope: result.scope,
            structure: result.structure,
        });

        return result;
    }
}
